# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import qhali_pb2 as qhali__pb2


class SpeechRecognitionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.tts = channel.unary_unary(
                '/qhali.SpeechRecognition/tts',
                request_serializer=qhali__pb2.TTSRequest.SerializeToString,
                response_deserializer=qhali__pb2.TTSResponse.FromString,
                )
        self.stt = channel.unary_unary(
                '/qhali.SpeechRecognition/stt',
                request_serializer=qhali__pb2.STTRequest.SerializeToString,
                response_deserializer=qhali__pb2.STTResponse.FromString,
                )


class SpeechRecognitionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def tts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'tts': grpc.unary_unary_rpc_method_handler(
                    servicer.tts,
                    request_deserializer=qhali__pb2.TTSRequest.FromString,
                    response_serializer=qhali__pb2.TTSResponse.SerializeToString,
            ),
            'stt': grpc.unary_unary_rpc_method_handler(
                    servicer.stt,
                    request_deserializer=qhali__pb2.STTRequest.FromString,
                    response_serializer=qhali__pb2.STTResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qhali.SpeechRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpeechRecognition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def tts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qhali.SpeechRecognition/tts',
            qhali__pb2.TTSRequest.SerializeToString,
            qhali__pb2.TTSResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qhali.SpeechRecognition/stt',
            qhali__pb2.STTRequest.SerializeToString,
            qhali__pb2.STTResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
