# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qhali.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qhali.proto',
  package='qhali',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bqhali.proto\x12\x05qhali\"*\n\nTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\"\x1c\n\x0bTTSResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\x1b\n\nSTTRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"$\n\x0bSTTResponse\x12\x15\n\rtranscription\x18\x01 \x01(\t2o\n\x11SpeechRecognition\x12,\n\x03tts\x12\x11.qhali.TTSRequest\x1a\x12.qhali.TTSResponse\x12,\n\x03stt\x12\x11.qhali.STTRequest\x1a\x12.qhali.STTResponseb\x06proto3'
)




_TTSREQUEST = _descriptor.Descriptor(
  name='TTSRequest',
  full_name='qhali.TTSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='qhali.TTSRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region', full_name='qhali.TTSRequest.region', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=64,
)


_TTSRESPONSE = _descriptor.Descriptor(
  name='TTSResponse',
  full_name='qhali.TTSResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='qhali.TTSResponse.audio', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=94,
)


_STTREQUEST = _descriptor.Descriptor(
  name='STTRequest',
  full_name='qhali.STTRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='qhali.STTRequest.audio', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=123,
)


_STTRESPONSE = _descriptor.Descriptor(
  name='STTResponse',
  full_name='qhali.STTResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transcription', full_name='qhali.STTResponse.transcription', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['TTSRequest'] = _TTSREQUEST
DESCRIPTOR.message_types_by_name['TTSResponse'] = _TTSRESPONSE
DESCRIPTOR.message_types_by_name['STTRequest'] = _STTREQUEST
DESCRIPTOR.message_types_by_name['STTResponse'] = _STTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TTSRequest = _reflection.GeneratedProtocolMessageType('TTSRequest', (_message.Message,), {
  'DESCRIPTOR' : _TTSREQUEST,
  '__module__' : 'qhali_pb2'
  # @@protoc_insertion_point(class_scope:qhali.TTSRequest)
  })
_sym_db.RegisterMessage(TTSRequest)

TTSResponse = _reflection.GeneratedProtocolMessageType('TTSResponse', (_message.Message,), {
  'DESCRIPTOR' : _TTSRESPONSE,
  '__module__' : 'qhali_pb2'
  # @@protoc_insertion_point(class_scope:qhali.TTSResponse)
  })
_sym_db.RegisterMessage(TTSResponse)

STTRequest = _reflection.GeneratedProtocolMessageType('STTRequest', (_message.Message,), {
  'DESCRIPTOR' : _STTREQUEST,
  '__module__' : 'qhali_pb2'
  # @@protoc_insertion_point(class_scope:qhali.STTRequest)
  })
_sym_db.RegisterMessage(STTRequest)

STTResponse = _reflection.GeneratedProtocolMessageType('STTResponse', (_message.Message,), {
  'DESCRIPTOR' : _STTRESPONSE,
  '__module__' : 'qhali_pb2'
  # @@protoc_insertion_point(class_scope:qhali.STTResponse)
  })
_sym_db.RegisterMessage(STTResponse)



_SPEECHRECOGNITION = _descriptor.ServiceDescriptor(
  name='SpeechRecognition',
  full_name='qhali.SpeechRecognition',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=163,
  serialized_end=274,
  methods=[
  _descriptor.MethodDescriptor(
    name='tts',
    full_name='qhali.SpeechRecognition.tts',
    index=0,
    containing_service=None,
    input_type=_TTSREQUEST,
    output_type=_TTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='stt',
    full_name='qhali.SpeechRecognition.stt',
    index=1,
    containing_service=None,
    input_type=_STTREQUEST,
    output_type=_STTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECHRECOGNITION)

DESCRIPTOR.services_by_name['SpeechRecognition'] = _SPEECHRECOGNITION

# @@protoc_insertion_point(module_scope)
